### ISSUE TITLE
Translating to llvm-hs?

### ISSUE THREAD

**Issue by sdiehl** [tvh/llvm-general-quote#6]
Hi Timo,

There's a lot of nice work in this project, but since ``llvm-general`` isn't really maintained anymore how would you feel about the [`llvm-hs`](https://github.com/llvm-hs) team migrating a bunch of this work over to the new bindings? Would you mind if we forked this work on the parser so we're not duplicating work that's already been done?

**Comment by tvh** [comment]
Sure, go ahead!
